[platformio]
src_dir = .
default_envs = mega16

[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
lib_deps = olikraus/U8g2

[env:mega16]
build_flags = -D RELAY_COUNT=16

[env:mega32]
build_flags = -D RELAY_COUNT=32
